creatframe('o2ky',3,8,'The max|K|',3,...
    'mgwd',['Note: This parameter should be incall first by ''global''' ,...
        '\newline     and need another variable for inverse named ???m1'],...
    'pattern','cylinder','\omega',1.2,'k_y or \theta',[-1:0.1:1]*0.5,'folder','data');
